name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v4.3.0 11d5960

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v5 # v5.0.0 a0853c2
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
